export const STATUTORY_FUNDS = [
  {
    category: "(A) GRANTS, CONTRIBUTION AVAILABLE FROM THE CENTRAL OR THE STATE GOVERNMENT OR THE ZILLA PARISHAD/ PANCHAYAT SAMITI",
    funds: [
      "Mahatma Gandhi National Rural Employment Gurantee Scheme (MGNREGS)",
      "15th CFC",
      "5th SFC",
      "Performance Based Grant (CFC)",
      "Uttar Banga Unnayan Parishad (UBUP)",
      "Mission Nirmal Bangla ( MNB)/ Swarcha Bharat Mission",
      "Community Health Care & Management Innitiative (CHCMI)/NRHM",
      "National Rural Livelihood Mission (NRLM)",
      "Sahay Fund",
      "Hariyali",
      "Village Water & Sanitation Committee (VWSC)",
      "Paschimanchal Unnayan Parishad (PUP)",
      "Strengthening Rural Decentralization",
      "Backward Region Grant Fund (BRGF)",
      "Solid Waste Management (SWM)",
      "Integrated Tribal Development Programme (ITDP)",
      "Rastriya Krishi Vikash Yojana (RKVY)",
      "Samabathy Programme",
      "Border Area Development Fund (BADF)",
      "Panchayat Samity Fund",
      "Zilla Parishad Fund",
      "Grant for Five Year Plan (5YP)",
      "Gram Panchayat Staff Salary",
      "Honorarium of Prodhan",
      "Honorarium of Upa-Prodhan",
      "Honorarium of Sanchalaks",
      "FTA of General Members (including PS Members)",
      "Allowance of Tax Collector",
      "Sarba Siksha Abhiyan (SSA)",
      "Panchayat Swasakti Puruskar (PSP)",
      "Rastriya Gram Swaraj Yojana (RGSA)",
      "Public Health Engineering Department (PHED)",
      "Vector Borne Disease",
      "Fund from Siliguri Mahakuma Parishad",
      "NSAP",
      "PMAY-G",
      "SHC",
      "Contingency",
    ],
  },
  {
    category: "(B) OWN SOURCES REVENUE LIKE TAX, RATE, FEES, TOLLS, DONATION ETC.",
    funds: [
      "Own Fund (OSR)",
      "Land & House Tax",
      "Trade Registration Fees",
      "Building Plan Approval",
      "Sale of Tender Form",
      "Rent",
      "Mobile Tower",
      "Sale of Scrap Material",
      "Sale of tree",
      "Lease",
      "Toll",
      "Any Other Sourcess Not Specied Above",
    ],
  },
  {
    category: "(C) OTHER RECEIPTS/ EXPENDITURE",
    funds: [
      "Bidhayak Elaka Unnayan Parishad (BEUP)",
      "M.P.Local Area Development Fund (MPLAD)",
      "Performance Based Grant (ISGPP-II)/ PBG-IBRD",
      "Minority Development Fund (MDF)",
    ],
  },
  {
    category: "(D) LOANS/ ADVANCE/DEPOSITS",
    funds: [
      "Earnest Money",
      "Security Deposit",
      "PROFLAL",
      "Income Tax (IT)",
      "STDs/Goods & Service Tax (GST)",
      "Labour Welfare Cess",
      "Royalty",
    ],
  },
  {
    category: "(E) INTEREST ON DIPOSITS IN BANK/POST OFFICE",
    funds: ["INTEREST ON DIPOSITS IN BANK/POST OFFICE"],
  },
  {
    category: "(F) MISC. RECEIPT, IF ANY, NOT CLASSIFIED ABOVE",
    funds: ["MISC. RECEIPT, IF ANY, NOT CLASSIFIED ABOVE"],
  },
];

export const FLAT_STATUTORY_FUNDS = STATUTORY_FUNDS.flatMap((cat) => cat.funds);
